### ISSUE TITLE
Complete OpenPTV-like example 

### ISSUE THREAD

**Issue by alexlib** [ronshnapp/MyPTV#4]
@ronshnapp it would be great if we consider a few things that will make all the adoption easier:
1. one complete experiment example - e.g. https://github.com/openptv/test_cavity, along with the post-processing and plots, or maybe your jet on figshare
2. we can do a zoom chat with you explaining to me all the analysis and all the insight and we record it as a tutorial for the followers

**Comment by ronshnapp** [comment]
Yes, examples are needed. I'll prepare synthetic images, and make a tutorial notebook.
This will also be a good opportunity to sort out an easy workflow with the code.

**Comment by alexlib** [comment]
If you teach me, we both learn and record it.
________________________________

**Comment by alexlib** [comment]
@ronshnapp I try to convert `test_cavity` into `test_cavity_myptv` folder but couldn't manage. Although apparently we use the same pinhole model from Maas, the f-number is very different (we count in tens, 20-100, probably millimetres) and you in thousands (not sure about units). Furthermore, some other parameters are probably different. 
If we could zoom over the calibration of one camera (from scratch) - it would help.

**Comment by ronshnapp** [comment]
Yes, the models are slightly different. First, the "f" in MyPTV is the focal length in units of pixels, whereas it is in mm in the Mass model (that's why in OpenPTV you also need to put in the pixel size). Second, MyPTV uses the multimedia + radial + tangential + affine correction terms, while MyPTV uses a general 2nd order polynomial as the non-linear correction. All of this is explained in Sec.1.2 in the manual.
Yes, let's do a Zoom - I may be able to do today. If not, we could do on Friday, or next week.
